### ISSUE TITLE
4.0.0-0 prerelease accidentally still requires bluebird

### ISSUE THREAD

**Issue by james-rabbit** [luin/ioredis#650]
I get `Error: Cannot find module 'bluebird'` when running the 4.0.0-0 prerelease of ioredis.

https://github.com/luin/ioredis/blob/4c95057733281a6d4b184cc3a6736076ee633e0a/index.js#L6

**Comment by luin** [comment]
Just fixed in 4.0.0-1. Sorry for the inconvenient.

**Comment by james-rabbit** [comment]
Thank you, this works in 4.0.0-1 prerelease.
